<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="A fully featured admin theme which can be used to build CRM, CMS, etc.">
    <meta name="author" content="Coderthemes">

    <!-- App Favicon -->
    <link rel="shortcut icon" href="<?= $this->url->get('') ?>assets/images/favicon.ico">

    <!-- App title -->
    <title>Uplon - Bootstrap 4 Responsive Admin Dashboard Template</title>

    <!-- DataTables -->
    <link href="<?= $this->url->get('') ?>plugins/datatables/dataTables.bootstrap4.min.css" rel="stylesheet"
          type="text/css"/>
    <link href="<?= $this->url->get('') ?>plugins/datatables/buttons.bootstrap4.min.css" rel="stylesheet"
          type="text/css"/>
    <!-- Responsive datatable examples -->
    <link href="<?= $this->url->get('') ?>plugins/datatables/responsive.bootstrap4.min.css" rel="stylesheet"
          type="text/css"/>
    <!-- Multi Item Selection examples -->
    <link href="<?= $this->url->get('') ?>plugins/datatables/select.bootstrap4.min.css" rel="stylesheet"
          type="text/css"/>

    <!-- Switchery css -->
    <link href="<?= $this->url->get('') ?>plugins/switchery/switchery.min.css" rel="stylesheet"/>

    <!-- Bootstrap CSS -->
    <link href="<?= $this->url->get('') ?>assets/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>

    <!-- App CSS -->
    <link href="<?= $this->url->get('') ?>assets/css/style.css" rel="stylesheet" type="text/css"/>

    <!-- Modernizr js -->
    <script src="<?= $this->url->get('') ?>assets/js/modernizr.min.js"></script>

</head>


<body class="fixed-left">

<!-- Begin page -->
<div id="wrapper">

    <!-- Top Bar Start -->
    <div class="topbar">

        <!-- LOGO -->
        <div class="topbar-left">
            <a href="<?= $this->url->get('') ?>" class="logo">
                <img src="<?= $this->url->get('img/bot-logo.png') ?>" width="150px" class="img-responsive" alt="">
            </a>
        </div>

        <nav class="navbar-custom">

            <ul class="list-inline float-right mb-0">
                <li class="list-inline-item dropdown notification-list">
                    <a class="nav-link dropdown-toggle arrow-none waves-light waves-effect" data-toggle="dropdown"
                       href="#" role="button"
                       aria-haspopup="false" aria-expanded="false">
                        <i class="zmdi zmdi-notifications-none noti-icon"></i>
                        <span class="noti-icon-badge"></span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right dropdown-arrow dropdown-lg" aria-labelledby="Preview">
                        <!-- item-->
                        <div class="dropdown-item noti-title">
                            <h5>
                                <small><span class="badge badge-danger">7</span>Notification</small>
                            </h5>
                        </div>

                        <!-- item-->
                        <a href="javascript:void(0);" class="dropdown-item notify-item">
                            <div class="notify-icon bg-success"><i class="icon-bubble"></i></div>
                            <p class="notify-details">Robert S. Taylor commented on Admin
                                <small class="text-muted">1min ago</small>
                            </p>
                        </a>

                        <!-- item-->
                        <a href="javascript:void(0);" class="dropdown-item notify-item">
                            <div class="notify-icon bg-info"><i class="icon-user"></i></div>
                            <p class="notify-details">New user registered.
                                <small class="text-muted">1min ago</small>
                            </p>
                        </a>

                        <!-- item-->
                        <a href="javascript:void(0);" class="dropdown-item notify-item">
                            <div class="notify-icon bg-danger"><i class="icon-like"></i></div>
                            <p class="notify-details">Carlos Crouch liked <b>Admin</b>
                                <small class="text-muted">1min ago</small>
                            </p>
                        </a>

                        <!-- All-->
                        <a href="javascript:void(0);" class="dropdown-item notify-item notify-all">
                            View All
                        </a>

                    </div>
                </li>


                <li class="list-inline-item dropdown notification-list">
                    <a class="nav-link waves-effect waves-light right-bar-toggle" href="javascript:void(0);">
                        <i class="zmdi zmdi-format-subject noti-icon"></i>
                    </a>
                </li>

                <li class="list-inline-item dropdown notification-list">
                    <a class="nav-link dropdown-toggle waves-effect waves-light nav-user" data-toggle="dropdown"
                       href="#" role="button"
                       aria-haspopup="false" aria-expanded="false">
                        <img src="<?= $this->url->get('') ?>assets/images/users/avatar-1.jpg" alt="user"
                             class="rounded-circle">
                    </a>
                    <div class="dropdown-menu dropdown-menu-right profile-dropdown " aria-labelledby="Preview">
                        <!-- item-->
                        <div class="dropdown-item noti-title">
                            <h5 class="text-overflow">
                                <small>Welcome ! John</small>
                            </h5>
                        </div>

                        <!-- item-->
                        <a href="javascript:void(0);" class="dropdown-item notify-item">
                            <i class="zmdi zmdi-account-circle"></i> <span>Profile</span>
                        </a>

                        <!-- item-->
                        <a href="javascript:void(0);" class="dropdown-item notify-item">
                            <i class="zmdi zmdi-power"></i> <span>Logout</span>
                        </a>

                    </div>
                </li>

            </ul>

            <ul class="list-inline menu-left mb-0">
                <li class="float-left">
                    <button class="button-menu-mobile open-left waves-light waves-effect">
                        <i class="zmdi zmdi-menu"></i>
                    </button>
                </li>
                <li class="hidden-mobile app-search">
                    <form role="search" class="">
                        <input type="text" placeholder="Search..." class="form-control">
                        <a href=""><i class="fa fa-search"></i></a>
                    </form>
                </li>
            </ul>

        </nav>

    </div>
    <!-- Top Bar End -->


    <!-- ========== Left Sidebar Start ========== -->
    <div class="left side-menu">
        <div class="sidebar-inner slimscrollleft">

            <!--- Sidemenu -->
            <div id="sidebar-menu">
                <ul>
                    <li class="text-muted menu-title">Navigation</li>

                    <li class="has_sub">
                        <a href="<?= $this->url->get('index') ?>" class="waves-effect"><i
                                    class="zmdi zmdi-view-dashboard"></i><span> Dashboard </span> </a>
                    </li>
                    <li class="has_sub">
                        <a href="<?= $this->url->get('prestashop/index') ?>"
                           class="waves-effect"><i class="zmdi zmdi-view-list">

                            </i><span> Prestashop </span> </a>
                    </li>

                </ul>
                <div class="clearfix"></div>
            </div>
            <!-- Sidebar -->
            <div class="clearfix"></div>

        </div>

    </div>
    <!-- Left Sidebar End -->


    <!-- ============================================================== -->
    <!-- Start right Content here -->
    <!-- ============================================================== -->
    <div class="content-page">
        <!-- Start content -->
        <div class="content">
            <div class="container-fluid">

                <div class="row">
                    <div class="col-xl-12">
                        <div class="page-title-box">
                            <h4 class="page-title float-left">Dashboard</h4>

                            <div class="clearfix"></div>
                        </div>
                    </div>
                </div>
                <!-- end row -->
                <?= $this->flashSession->output() ?>
                <?= $this->getContent() ?>
            </div> <!-- container -->

        </div> <!-- content -->


    </div>
    <!-- End content-page -->


    <!-- ============================================================== -->
    <!-- End Right content here -->
    <!-- ============================================================== -->


    <!-- Right Sidebar -->
    <div class="side-bar right-bar">
        <div class="nicescroll">
            <ul class="nav nav-pills nav-justified">
                <li class="nav-item">
                    <a href="#home-2" class="nav-link active" data-toggle="tab" aria-expanded="false">
                        Activity
                    </a>
                </li>
                <li class="nav-item">
                    <a href="#messages-2" class="nav-link" data-toggle="tab" aria-expanded="true">
                        Settings
                    </a>
                </li>
            </ul>

            <div class="tab-content">
                <div class="tab-pane fade active show" id="home-2">
                    <div class="timeline-2">
                        <div class="time-item">
                            <div class="item-info">
                                <small class="text-muted">5 minutes ago</small>
                                <p><strong><a href="#" class="text-info">John Doe</a></strong> Uploaded a photo <strong>"DSC000586.jpg"</strong>
                                </p>
                            </div>
                        </div>

                        <div class="time-item">
                            <div class="item-info">
                                <small class="text-muted">30 minutes ago</small>
                                <p><a href="" class="text-info">Lorem</a> commented your post.</p>
                                <p><em>"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam laoreet tellus
                                        ut tincidunt euismod. "</em></p>
                            </div>
                        </div>

                        <div class="time-item">
                            <div class="item-info">
                                <small class="text-muted">59 minutes ago</small>
                                <p><a href="" class="text-info">Jessi</a> attended a meeting with<a href="#"
                                                                                                    class="text-success">John
                                        Doe</a>.</p>
                                <p><em>"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam laoreet tellus
                                        ut tincidunt euismod. "</em></p>
                            </div>
                        </div>

                        <div class="time-item">
                            <div class="item-info">
                                <small class="text-muted">1 hour ago</small>
                                <p><strong><a href="#" class="text-info">John Doe</a></strong>Uploaded 2 new photos</p>
                            </div>
                        </div>

                        <div class="time-item">
                            <div class="item-info">
                                <small class="text-muted">3 hours ago</small>
                                <p><a href="" class="text-info">Lorem</a> commented your post.</p>
                                <p><em>"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam laoreet tellus
                                        ut tincidunt euismod. "</em></p>
                            </div>
                        </div>

                        <div class="time-item">
                            <div class="item-info">
                                <small class="text-muted">5 hours ago</small>
                                <p><a href="" class="text-info">Jessi</a> attended a meeting with<a href="#"
                                                                                                    class="text-success">John
                                        Doe</a>.</p>
                                <p><em>"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam laoreet tellus
                                        ut tincidunt euismod. "</em></p>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="tab-pane fade" id="messages-2">

                    <div class="row m-t-10">
                        <div class="col-8">
                            <h5 class="m-0">Notifications</h5>
                            <p class="text-muted m-b-0">
                                <small>Do you need them?</small>
                            </p>
                        </div>
                        <div class="col-4 text-right">
                            <input type="checkbox" checked data-plugin="switchery" data-color="#1bb99a"
                                   data-size="small"/>
                        </div>
                    </div>

                    <div class="row m-t-10">
                        <div class="col-8">
                            <h5 class="m-0">API Access</h5>
                            <p class="m-b-0 text-muted">
                                <small>Enable/Disable access</small>
                            </p>
                        </div>
                        <div class="col-4 text-right">
                            <input type="checkbox" checked data-plugin="switchery" data-color="#1bb99a"
                                   data-size="small"/>
                        </div>
                    </div>

                    <div class="row m-t-10">
                        <div class="col-8">
                            <h5 class="m-0">Auto Updates</h5>
                            <p class="m-b-0 text-muted">
                                <small>Keep up to date</small>
                            </p>
                        </div>
                        <div class="col-4 text-right">
                            <input type="checkbox" checked data-plugin="switchery" data-color="#1bb99a"
                                   data-size="small"/>
                        </div>
                    </div>

                    <div class="row m-t-10">
                        <div class="col-8">
                            <h5 class="m-0">Online Status</h5>
                            <p class="m-b-0 text-muted">
                                <small>Show your status to all</small>
                            </p>
                        </div>
                        <div class="col-4 text-right">
                            <input type="checkbox" checked data-plugin="switchery" data-color="#1bb99a"
                                   data-size="small"/>
                        </div>
                    </div>

                </div>
            </div>
        </div> <!-- end nicescroll -->
    </div>
    <!-- /Right-bar -->

    <footer class="footer">
        2016 - 2019 © Uplon.
    </footer>


</div>
<!-- END wrapper -->


<script>
    var resizefunc = [];
</script>

<!-- jQuery  -->
<script src="<?= $this->url->get('') ?>assets/js/jquery.min.js"></script>
<script src="<?= $this->url->get('') ?>assets/js/bootstrap.bundle.min.js"></script>
<script src="<?= $this->url->get('') ?>assets/js/detect.js"></script>
<script src="<?= $this->url->get('') ?>assets/js/fastclick.js"></script>
<script src="<?= $this->url->get('') ?>assets/js/jquery.blockUI.js"></script>
<script src="<?= $this->url->get('') ?>assets/js/waves.js"></script>
<script src="<?= $this->url->get('') ?>assets/js/jquery.nicescroll.js"></script>
<script src="<?= $this->url->get('') ?>assets/js/jquery.scrollTo.min.js"></script>
<script src="<?= $this->url->get('') ?>assets/js/jquery.slimscroll.js"></script>
<script src="<?= $this->url->get('') ?>plugins/switchery/switchery.min.js"></script>

<!-- Required datatable js -->
<script src="<?= $this->url->get('') ?>plugins/datatables/jquery.dataTables.min.js"></script>
<script src="<?= $this->url->get('') ?>plugins/datatables/dataTables.bootstrap4.min.js"></script>
<!-- Buttons examples -->
<script src="<?= $this->url->get('') ?>plugins/datatables/dataTables.buttons.min.js"></script>
<script src="<?= $this->url->get('') ?>plugins/datatables/buttons.bootstrap4.min.js"></script>
<script src="<?= $this->url->get('') ?>plugins/datatables/jszip.min.js"></script>
<script src="<?= $this->url->get('') ?>plugins/datatables/pdfmake.min.js"></script>
<script src="<?= $this->url->get('') ?>plugins/datatables/vfs_fonts.js"></script>
<script src="<?= $this->url->get('') ?>plugins/datatables/buttons.html5.min.js"></script>
<script src="<?= $this->url->get('') ?>plugins/datatables/buttons.print.min.js"></script>

<!-- Key Tables -->
<script src="<?= $this->url->get('') ?>plugins/datatables/dataTables.keyTable.min.js"></script>

<!-- Responsive examples -->
<script src="<?= $this->url->get('') ?>plugins/datatables/dataTables.responsive.min.js"></script>
<script src="<?= $this->url->get('') ?>plugins/datatables/responsive.bootstrap4.min.js"></script>

<!-- Selection table -->
<script src="<?= $this->url->get('') ?>plugins/datatables/dataTables.select.min.js"></script>

<!-- App js -->
<script src="<?= $this->url->get('') ?>assets/js/jquery.core.js"></script>
<script src="<?= $this->url->get('') ?>assets/js/jquery.app.js"></script>

<script src="<?= $this->url->get('js/c1.js') ?>"></script>

</body>
</html>